plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-cs24.github.io 
baseurl: "/s19"  

name: "CS 24 Spring 2019"
course: "CS24"
course_title: "Problem Solving with Computers II"
title: "UCSB CS24 S19"
github_url: https://github.com/ucsb-cs24/s19
qtr: "S19"
quarter: "Spring 2019"
lecture_times: "MW 9:30am - 10:45am"
lecture_location: "PSYCH 1924"
lab_times: "Tuesdays: 3p, 4p, 5p, 6p"
tas: "Mohith Pukale, Dheeraj  Baby"
tutors: "
Tina  Shi
Adarsha Poudel
Lily  Ou
Aesha Parekh
Madhu Kannan
Eliza Ruiz
Jared Flores
Arthur  Gatin
"
class_org:
   name: ucsb-cs24-s19-mirza 
   url: https://github.com/ucsb-cs24-s19-mirza

start_week: 1
start_date: 2019-03-31 
num_weeks: 10
extra_exam_week: true

instructor_url: https://ucsb-cs24.github.io/instructor

cal_dates: >
  [
  {"label":"First day of classes", "date":"2019-04-01" },
  {"label":"Univ Holiday", "date":"2019-05-27" },
  {"label":"Drop deadline (no W grade)","date":"2019-04-26" },
  {"label":"S19 Instruction Ends", "date":"2019-06-07" },  
  {"label":"S19 Quarter Ends", "date":"2019-06-14" }          
  ]

kramdown:
   parse_block_html: true

exclude:
   - vendor
include:
  - _pages

timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  pa:
    output: true
    permalink: /pa/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  -
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  -
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  -
    scope:
      path: ""
      type: pa
    values:
      layout: lab
  -
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  -
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
